mqtt:
  host: docker-pi
http:
  port: 9131
sensors:
- topic: 'power-meter/household'
  field: ['currentConsumption', 'totalConsumption', 'totalDelivery']
  id: household
  type: power
- topic: 'power-meter/heatpump'
  field: ['currentConsumption', 'totalConsumption']
  id: heatpump
  type: power
- topic: 'heatpump/#'
  type: heatpump
- topic: 'zigbee2mqtt/+'
  field: [ 'temperature', 'humidity', 'pressure', 'battery', 'linkquality' ]
  type: aqara
