mqtt:
  host: localhost
http:
  port: 9131
sensors:
- topic: 'power-meter/household/consumption'
  field: ['current', 'total']
  id: household
  type: power
- topic: 'power-meter/heatpump/consumption'
  field: ['current', 'total']
  id: heatpump
  type: power
- topic: 'heatpump/#'
  type: heatpump
- topic: 'zigbee2mqtt/+'
  field: [ 'temperature', 'humidity', 'pressure', 'battery', 'linkquality' ]
  type: aqara
